spring.application.name=wallet
server.port=81

# Cache (rpc waste prevention)
spring.cache.cache-names=balanceCache
spring.cache.caffeine.spec=maximumSize=1000,expireAfterWrite=10s

# rpc url Env Value
web3.rpc-url=${ETH_RPC_URL:}

# JWT Security Env Value
jwt.secret=${JWT_SECRET_KEY:}
# access token 5 minute
jwt.expiration=300000
# refresh token 1 hour
jwt.refreshexpiration=3600000